services:
  app_backend:
#    image:
    build:
      context: ../
      dockerfile: ./Dockerfile
    restart: always
    container_name: app_backend
    expose:
      - 8000
    networks:
      - easyRights
    depends_on:
      - traefik
    environment:
      HOST: app_backend
      PORT: 8000
    command: bash -c "/app/wait-for.sh sonar_core:8081 -- gunicorn --workers 3 --bind $$GOOGLE_SEARCH_HOST:$$GOOGLE_SEARCH_PORT --chdir '/app' app:app"


volumes:
  elasticsearch_data:
  reverse_proxy_nginx:
  sonar_core:
  redis:

networks:
    easyRights:
        driver: bridge